# -*- coding: utf-8 -*-
"""Untitled74.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-jug7gBGidt1qjbNtpKf5q9X2N9vatz
"""



import numpy as np
import matplotlib.pyplot as plt

# 1) Synthetic recruitment-curve generator (sigmoid)
def sigmoid(x, baseline, max_resp, x50, slope):
    return baseline + (max_resp - baseline) / (1 + np.exp(-(x - x50) / slope))

rng = np.random.default_rng(42)

# Synthetic stimulus intensities (e.g., normalized)
x = np.linspace(0.2, 2.0, 30)

# Ground-truth parameters (unknown to the "model")
true_params = dict(baseline=0.05, max_resp=1.2, x50=1.1, slope=0.15)
y_true = sigmoid(x, **true_params)

# Add noise (MEP data is noisy)
y = np.clip(y_true + rng.normal(0, 0.08, size=x.shape), 0, None)

# 2) Fit curve via lightweight random search (no scipy needed)
def fit_random_search(x, y, n_trials=8000, seed=0):
    rng = np.random.default_rng(seed)
    best = None
    best_loss = np.inf

    # Parameter ranges (reasonable for MEP amplitude)
    for _ in range(n_trials):
        baseline = rng.uniform(0.0, 0.2)
        max_resp = rng.uniform(0.3, 2.0)
        x50 = rng.uniform(0.4, 1.8)
        slope = rng.uniform(0.05, 0.6)

        y_hat = sigmoid(x, baseline, max_resp, x50, slope)
        loss = np.mean((y - y_hat) ** 2)

        if loss < best_loss:
            best_loss = loss
            best = (baseline, max_resp, x50, slope)

    return best, best_loss

best_params, best_loss = fit_random_search(x, y, n_trials=12000, seed=1)

# 3) Bootstrap for uncertainty band (posterior-like intervals)
def bootstrap_band(x, y, n_boot=200, seed=123):
    rng = np.random.default_rng(seed)
    curves = []

    n = len(x)
    for b in range(n_boot):
        idx = rng.integers(0, n, size=n)  # resample with replacement
        xb = x[idx]
        yb = y[idx]

        # Fit on bootstrap sample (reduce trials for speed)
        params_b, _ = fit_random_search(xb, yb, n_trials=4000, seed=seed + b)
        curves.append(sigmoid(x, *params_b))

    curves = np.array(curves)
    lo = np.percentile(curves, 5, axis=0)
    hi = np.percentile(curves, 95, axis=0)
    med = np.percentile(curves, 50, axis=0)
    return med, lo, hi

y_fit = sigmoid(x, *best_params)
y_med, y_lo, y_hi = bootstrap_band(x, y, n_boot=250)

# 4) Plot
plt.figure()
plt.scatter(x, y, label="Synthetic MEP observations")
plt.plot(x, y_fit, label="Fitted recruitment curve")
plt.fill_between(x, y_lo, y_hi, alpha=0.2, label="Uncertainty band (5–95%)")
plt.xlabel("Stimulation intensity (a.u.)")
plt.ylabel("MEP amplitude (a.u.)")
plt.title("Recruitment Curve Fit with Uncertainty Band")
plt.legend()
plt.show()

print("Best-fit params (baseline, max_resp, x50, slope):", best_params)
print("Fit MSE:", best_loss)



plt.savefig("recruitment_curve_uncertainty.png", dpi=300, bbox_inches="tight")